---
genPolicy: "Create"
openAPISpec: "http://18.144.38.115:8090/v2/api-docs"
generators:
- type: "anonymous_invalid"
  assertions:
  - "@StatusCode != 200"
  severity: "Critical"
  database: null
  inactive: true
  autoCodeGeneratorMatches: []
- type: "auth_invalid"
  assertions:
  - "@StatusCode != 200"
  severity: "Critical"
  database: null
  inactive: true
  autoCodeGeneratorMatches: []
- type: "ddos"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401\n@StatusCode != 404\n@StatusCode != 500"
  severity: "Critical"
  database: null
  inactive: true
  autoCodeGeneratorMatches: []
- type: "XSS_Injection"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401\n@StatusCode != 404\n@StatusCode != 500"
  severity: "Critical"
  database: null
  inactive: false
  autoCodeGeneratorMatches: []
- type: "sql_injection"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401\n@StatusCode != 404\n@StatusCode != 500"
  severity: "Critical"
  database:
    name: "MySQL"
    version: "5.7"
  inactive: true
  autoCodeGeneratorMatches: []
- type: "sql_injection_timebound"
  assertions:
  - "@ResponseTime >= 5000"
  - "@StatusCode != 401\n@StatusCode != 404\n@StatusCode != 500"
  severity: "Critical"
  database:
    name: "MySQL"
    version: "5.7"
  inactive: true
  autoCodeGeneratorMatches: []
- type: "log_Forging"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401\n@StatusCode != 404\n@StatusCode != 500"
  severity: "Critical"
  database: null
  inactive: true
  autoCodeGeneratorMatches: []
- type: "rbac"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401\n@StatusCode != 404\n@StatusCode != 500"
  severity: "Critical"
  database: null
  inactive: true
  autoCodeGeneratorMatches: []
- type: "invalid_datatype"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401\n@StatusCode != 404\n@StatusCode != 500"
  severity: "Critical"
  database: null
  inactive: true
  autoCodeGeneratorMatches: []
- type: "special_chars "
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401\n@StatusCode != 404\n@StatusCode != 500"
  severity: "Critical"
  database: null
  inactive: true
  autoCodeGeneratorMatches: []
- type: "anonymous_invalid"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401\n@StatusCode != 404\n@StatusCode != 500"
  severity: "Critical"
  database: null
  inactive: true
  autoCodeGeneratorMatches: []
- type: "empty_value"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401\n@StatusCode != 404\n@StatusCode != 500"
  severity: "Critical"
  database: null
  inactive: true
  autoCodeGeneratorMatches: []
- type: "create"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401\n@StatusCode != 404\n@StatusCode != 500"
  severity: "Critical"
  database: null
  inactive: false
  autoCodeGeneratorMatches: []
